# Generated by Django 4.0.4 on 2022-09-12 18:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='The format should be exactly be of 10 digits', regex='^\\+?1?\\d{10}$')])),
                ('dateTimeNow', models.DateTimeField(auto_now_add=True)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Buddy_S_User',
            fields=[
                ('B_Userid', models.AutoField(primary_key=True, serialize=False)),
                ('u_ID', models.CharField(max_length=30)),
                ('Busername', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='BuddyHome/images')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('usertype', models.CharField(choices=[('Principal', 'Principal'), ('HOD_S', 'HOD_S'), ('Special_Teacher', 'Special_Teacher'), ('Special_Student', 'Special_Student'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=20, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
