# Generated by Django 4.0.4 on 2022-09-12 18:29

import BuddyShare.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BuddyHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('FileDid', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.CharField(max_length=200)),
                ('tobeDelete', models.BooleanField(default=False)),
                ('TimeForDeletion', models.DateTimeField()),
                ('ShareWithEveryOne', models.BooleanField(default=True)),
                ('toShareWith', models.ManyToManyField(to='BuddyHome.buddy_s_user')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crated_at', models.DateField(auto_now=True)),
                ('FileUserData', models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.CASCADE, to='BuddyShare.filedata')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=BuddyShare.models.get_upload_path)),
                ('created_at', models.DateField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuddyShare.folder')),
            ],
        ),
    ]
