# Generated by Django 4.0.4 on 2022-09-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuddyShare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='TimeForDeletion',
            field=models.DateTimeField(blank=True),
        ),
        migrations.RemoveField(
            model_name='filedata',
            name='toShareWith',
        ),
        migrations.AddField(
            model_name='filedata',
            name='toShareWith',
            field=models.CharField(default='[]', max_length=100),
        ),
    ]
