# Generated by Django 4.0.4 on 2022-09-28 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuddyShare', '0003_alter_filedata_timefordeletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='FileUserData',
            field=models.ForeignKey(default='101', on_delete=django.db.models.deletion.CASCADE, to='BuddyShare.filedata'),
        ),
    ]
